# lec3 NumPy

# 外部ライブラリの使い方

In [10]:
#timeモジュールをインポート
import time
#1〜3まで繰り返す。
for count in range(1,4): 
    #1秒止まる
    time.sleep(1) 
     #経過秒数を出力
    print("{}秒経過".format(count))

1秒経過
2秒経過
3秒経過


In [11]:
for count in range(1,4): 
    #1秒止まる
    time.sleep(1) 
     #経過秒数を出力
    print(f"{count}秒経過")

1秒経過
2秒経過
3秒経過


## 外部ライブラリ 演習

問題１\
経過した「秒」を出力するプログラムを作成せよ\
ただしカウントが3の倍数の場合のみ数字ではなく文字列
"Python最高!"\
と出力せよ

In [13]:
import time 
#1〜15まで繰り返す
for count in range(1,16): 
    #カウントが３の倍数かどうかを判定する
    if count%3 == 0: #if文"=="のように=を二つ繋げる
        print("python")
    else :
        print("{}秒経過".format(count)) 
    time.sleep(1)

1秒経過
2秒経過
python
4秒経過
5秒経過
python
7秒経過
8秒経過
python
10秒経過
11秒経過
python
13秒経過
14秒経過
python


# Numpyで配列を高速に処理しよう

## NumPyとは?
・多次元かつ大量のベクトル，行列の演算が得意\
・中身がCを用いて実装されており処理が高速


## NumPy配列の作り方

In [14]:
#Numpyのインポート
import numpy as np 

In [15]:
#1次元の配列生成

#正
a = np.array([1, 2, 3]) 
#誤：エラーを生む
#a = np.array(1, 2, 3) 
a

array([1, 2, 3])

In [16]:
#２次元の配列生成

# 正
a = np.array([ [1, 2, 3],
              [4, 5, 6] ]) 

# 誤：エラーを生む
#a = np.array([1, 2, 3],
 #                 [4, 5, 6])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
a[0] #行列aの0行目

array([1, 2, 3])

In [18]:
a[1]

array([4, 5, 6])

In [19]:
a[0][1] #0行目の1列目

2

In [20]:
# ゼロ行列
zeros2x3 = np.zeros((2, 3))
zeros2x3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
# イチ行列
ones2x3 = np.ones((2,3))
ones2x3

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
# 0から始まる連続する10の整数の配列
print(np.arange(10))

#np.arange(始, 終, 間隔)
print(np.arange(10, 30, 5))
print(np.arange(0, 2, 0.3))

#等間隔な数列を生成(始, 終, 個数)
print(np.linspace(0, np.pi, 10))

[0 1 2 3 4 5 6 7 8 9]
[10 15 20 25]
[0.  0.3 0.6 0.9 1.2 1.5 1.8]
[0.         0.34906585 0.6981317  1.04719755 1.3962634  1.74532925
 2.0943951  2.44346095 2.7925268  3.14159265]


In [23]:
#6要素の配列を生成
array = np.array([1, 2, 3, 4, 5, 6])
array


array([1, 2, 3, 4, 5, 6])

In [24]:
#arrayを2x3行列に整形
arr2x3 = array.reshape(2, 3)

#! 割り切れない数字ではreshape不可
#arr4x2 = array.reshape(2, 4)
arr2x3

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
#行列を1次元に"ほどく "
a = arr2x3.ravel() 
a

array([1, 2, 3, 4, 5, 6])

In [26]:
#転置行列
a2x3_T = arr2x3.T
a2x3_T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [27]:
#transpose関数でも同様
arr2x3_transpose = arr2x3.transpose()
arr2x3_transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [28]:
a2x3_T == arr2x3_transpose

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

In [29]:
# .shapeで行と列の値を確認できる
a2x3_T.shape

(3, 2)

## NumPy配列の作り方 演習　問題１〜３

#### 問題1
0から14の連番が入った配列aを作成せよ

#### 問題2
配列aを3行5列に整形した配列bを作成せよ

#### 問題3
配列aとbの形状（行と列の数）を確認せよ

答え
<!--
#問題1
a = np.arange(15)
print(a)

#問題2
b = a.reshape(3,5)
print(b)

#問題3
print(a.shape)
print(b.shape)
-->

## NumPy配列に対する数学的な演算

In [30]:
a = np.array([0, 1, 2, 3, 9])
b = np.array([2, 4, 6, 0 , np.inf])
#足し算(+, np.add(a, b))
print(a+b)
#引き算(-, np.subtract(a, b))
print(a-b)
print(a-3)

[ 2.  5.  8.  3. inf]
[ -2.  -3.  -4.   3. -inf]
[-3 -2 -1  0  6]


In [31]:
print(a+3)

[ 3  4  5  6 12]


In [32]:
#引き算(-, np.subtract(a, b))
print(a-b)

[ -2.  -3.  -4.   3. -inf]


In [33]:
a = np.array([0, 1, 2, 3, 9])
b = np.array([2, 4, 6, 0 , np.inf])

#掛け算(*, np.multiply(a, b) )
print(f"a * b: {a * b}")

#累乗(**, np.power(a, b) )
print(f"a ** b: {a ** b}")

#平方根(np.sqrt(a), np.power(a, 1/2) )
print(f"np.sqrt(a): {np.sqrt(a)}")

a * b: [ 0.  4. 12.  0. inf]
a ** b: [ 0.  1. 64.  1. inf]
np.sqrt(a): [0.         1.         1.41421356 1.73205081 3.        ]


In [34]:
#割り算(/, np.divide(a, b) )
print(f"a / b: {a / b}")

#商の整数部分(//)
print(f"100 // b: {100 // b}")

#剰余(%,np.mod() )
print(f"100%b: {100 % b}")

a / b: [0.         0.25       0.33333333        inf 0.        ]
100 // b: [50. 25. 16. inf  0.]
100%b: [  0.   0.   4.  nan 100.]


/Users/tomiokakotaro/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  
/Users/tomiokakotaro/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in floor_divide
  """
/Users/tomiokakotaro/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: RuntimeWarning: invalid value encountered in remainder
  


In [35]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

#同じ要素番号同士の掛け算
print(A * B)

#行列の掛け算 (A.dot(B)でも可 )
print(np.dot(A,B))

[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [36]:
#統計的な計算

In [37]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [38]:
a.mean() # 平均値

3.0

In [39]:
print(f"a: {a}")
print(f"sum: {a.sum()}") # 和
print(f"min: {a.min()}") #最小値
print(f"max: {a.max()}") #最大値
print(f"aの分散は{a.var()},標準偏差は{a.std():.3f}です.")

a: [1 2 3 4 5]
sum: 15
min: 1
max: 5
aの分散は2.0,標準偏差は1.414です.


### "axis"について個人で調べてみましょう

In [40]:
b=np.arange(1,18,2).reshape(3,3)
print(f"b={b}")

#列ごとの和
b.sum(axis=0)
print(f"b.sum(axis=0)={b.sum(axis=0)}") #axis=0だと列ごと

#行中の最小値
b.min(axis=1)
print(f"b.min(axis=1)={b.min(axis=1)}") #axis=1だと行ごと

#各行までの累積和
print(b.cumsum(axis=0))

b=[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
b.sum(axis=0)=[21 27 33]
b.min(axis=1)=[ 1  7 13]
[[ 1  3  5]
 [ 8 12 16]
 [21 27 33]]


## 補足

In [41]:
#調べて指数関数を埋めてみよう

In [42]:
#円周率
np.pi

#三角関数
np.sin(np.pi)
np.cos(np.pi)
np.tan(np.pi) 

#逆三角関数
np.arcsin(1)
np.arccos(1)
np.arctan(1) 

#指数関数
np.exp(0)

#対数関数
np.log(1)
np.log10(1)

#絶対値
np.abs(1);


例
<!--
np.exp(0)
-->

In [43]:
np.exp(1)

2.718281828459045

## 配列内部のデータ参照

In [44]:
#適当な配列を用意した
a = np.array(list("あいうえお"))
a

array(['あ', 'い', 'う', 'え', 'お'], dtype='<U1')

In [45]:
#スライス：リストに対して一部のデータを取得する操作
a[0]

'あ'

In [46]:
a[3]

'え'

In [47]:
a[-1] #末尾から数えて1番目

'お'

In [48]:
a[-3]

'う'

In [49]:
# "あ"と"う"を取り出したい
a[[0,2]] # 引数にリストを与えた

array(['あ', 'う'], dtype='<U1')

In [50]:
a[0:2]

array(['あ', 'い'], dtype='<U1')

In [51]:
print(a[1:4])#["い","う","え"]
print(a[0:4:2])

['い' 'う' 'え']
['あ' 'う']


In [52]:
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
b[1][2]#1行2列目を取り出す

6

In [54]:
b[1,2]#行と列の数字は「,」で区切るのでも良い

6

In [55]:
b[1,:] #「:」は任意の意味

array([4, 5, 6])

In [56]:
b[:,2]#2列目を取り出す

array([3, 6])

In [57]:
b[:,[0,2]]#行は任意、0列目と2列目

array([[1, 3],
       [4, 6]])

In [58]:
# 0〜24の一次元配列を生成し、5次正方行列に変換
b = np.arange(25).reshape(5, 5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [59]:
#3列目の要素すべて
print(b[:,3] )
#2行3列目の要素
print(b[2,3] )

[ 3  8 13 18 23]
13


In [60]:
b[1:4,] #1行から3行

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [61]:
b[1:4:2, :] #1行と3行 

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19]])

In [62]:
#(1, 3)行と(1, 3)列が交わる
#2x2=4通りの組み合わせ
b[1:4:2, 1:4:2]  

array([[ 6,  8],
       [16, 18]])

In [63]:
#対角成分の表示(行列番号が同じ成分)
b[range(5),range(5)]

array([ 0,  6, 12, 18, 24])

In [64]:
#最終要素に存在する配列を取り出す
#この例はb[-1,:]と等価
b[-1] 

array([20, 21, 22, 23, 24])

In [65]:
#4x5の配列の生成
a = np.arange(20).reshape((4,5))
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [66]:
#np.where( (条件文),(真の場合の値),(偽の場合の値) )
#aの要素が3の倍数であれば1, そうでなければ0をかえす
b = np.where((a%3 == 0), 1, 0)
b

array([[1, 0, 0, 1, 0],
       [0, 1, 0, 0, 1],
       [0, 0, 1, 0, 0],
       [1, 0, 0, 1, 0]])

## 配列内部のデータ参照 演習

#### 問題1
1から25までの数字で5×5の配列を作れ\
[[ 1  2  3  4  5]\
 [ 6  7  8  9 10]\
 [11 12 13 14 15]\
 [16 17 18 19 20]\
 [21 22 23 24 25]]

#### 問題2
問題1から$array([[ 7,  8],
       [12, 13]])$
を出力せよ

答え
<!--
#問題1
array_1 = np.arange(1, 26).reshape(5, 5)
print(array_1)

#問題2
array_1[1:3,1:3]
-->

### 復習 

シグモイド関数を作る \
$\displaystyle y=\frac{1}{1+e^{(-x)}}$

In [ ]:
def sigmoid(x):
    return 

答え
<!--
1/(1+np.exp(-x))
-->

In [68]:
sigmoid(0) #0.5と出ると正解

NameError: name 'sigmoid' is not defined

#### 以下のNumpy配列Aに対して以下を出力せよ
問題1\
45

問題2\
array([6,15,24])

問題3\
array([12,15,18])

In [69]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

答え
<!--
問題1
np.sum(A)

問題2
A.sum(axis=1)

問題3
np.sum(A,axis = 0)
-->